CREATE TABLE `CARI_KART` (
  `ID` varchar(0) DEFAULT NULL,
  `UNVANI` varchar(0) DEFAULT NULL,
  `ADRES_1` varchar(0) DEFAULT NULL,
  `ADRES_2` varchar(0) DEFAULT NULL,
  `VERGI_DAIRESI` varchar(0) DEFAULT NULL,
  `VERGI_NO` varchar(0) DEFAULT NULL
);

CREATE TABLE `SABLON` (
  `ID` tinyint(4) DEFAULT NULL,
  `ACIKLAMA` varchar(46) DEFAULT NULL,
  `DOSYA_YOLU` varchar(52) DEFAULT NULL,
  `ISLEM_YERI` tinyint(4) DEFAULT NULL,
  `SORGU_GRUP` tinyint(4) DEFAULT NULL
);

CREATE TABLE `SATIS_FATURASI_ALT` (
  `ID` varchar(0) DEFAULT NULL,
  `TARIH` varchar(0) DEFAULT NULL,
  `FATURA_ID` varchar(0) DEFAULT NULL,
  `STOK_KART_ID` varchar(0) DEFAULT NULL,
  `STOK_KODU` varchar(0) DEFAULT NULL,
  `STOK_ADI` varchar(0) DEFAULT NULL,
  `MIKTAR` varchar(0) DEFAULT NULL,
  `BIRIM` varchar(0) DEFAULT NULL,
  `BIRIM_FIYAT` varchar(0) DEFAULT NULL,
  `ISKONTO_ORANI` varchar(0) DEFAULT NULL,
  `ISK_TUTAR` varchar(0) DEFAULT NULL,
  `ALT_ISK` varchar(0) DEFAULT NULL,
  `ALT_ISK_TUTAR` varchar(0) DEFAULT NULL,
  `KDV_DURUM` varchar(0) DEFAULT NULL,
  `KDV_ORANI` varchar(0) DEFAULT NULL,
  `TUTAR` varchar(0) DEFAULT NULL,
  `KDV_TUTARI` varchar(0) DEFAULT NULL,
  `INDIRIM_TUTARI` varchar(0) DEFAULT NULL,
  `MATRAH` varchar(0) DEFAULT NULL,
  `KDVLI_MATRAH` varchar(0) DEFAULT NULL,
  `SATIR_FIYAT` varchar(0) DEFAULT NULL,
  `SATIR_TUTAR` varchar(0) DEFAULT NULL
);

CREATE TABLE `SATIS_FATURASI_UST` (
  `ID` varchar(0) DEFAULT NULL,
  `CARI_KART_ID` varchar(0) DEFAULT NULL,
  `TARIH` varchar(0) DEFAULT NULL,
  `SAAT` varchar(0) DEFAULT NULL,
  `SERI` varchar(0) DEFAULT NULL,
  `EVRAK_NO` varchar(0) DEFAULT NULL,
  `VADE_TARIHI` varchar(0) DEFAULT NULL,
  `VADE` varchar(0) DEFAULT NULL,
  `SEVK_TARIHI` varchar(0) DEFAULT NULL,
  `SEVK_NO` varchar(0) DEFAULT NULL,
  `UNVANI` varchar(0) DEFAULT NULL,
  `ADRES_1` varchar(0) DEFAULT NULL,
  `ADRES_2` varchar(0) DEFAULT NULL,
  `VERGI_DAIRESI` varchar(0) DEFAULT NULL,
  `VERGI_NO` varchar(0) DEFAULT NULL,
  `TOPLAM` varchar(0) DEFAULT NULL,
  `ISKONTO_TOPLAM` varchar(0) DEFAULT NULL,
  `MATRAH` varchar(0) DEFAULT NULL,
  `KDV_TOPLAM` varchar(0) DEFAULT NULL,
  `GENEL_TOPLAM` varchar(0) DEFAULT NULL,
  `TESLIM_EDEN` varchar(0) DEFAULT NULL,
  `TESLIM_ALAN` varchar(0) DEFAULT NULL,
  `ACIKLAMA` varchar(0) DEFAULT NULL,
  `OZEL_ALAN_1` varchar(0) DEFAULT NULL,
  `OZEL_ALAN_2` varchar(0) DEFAULT NULL,
  `ALT_ISK_ORAN` varchar(0) DEFAULT NULL,
  `ALT_ISK_TUTAR` varchar(0) DEFAULT NULL,
  `ISLEM` varchar(0) DEFAULT NULL,
  `YUVARLA` varchar(0) DEFAULT NULL,
  `TEVKIFAT_PAY` varchar(0) DEFAULT NULL,
  `TEVKIFAT_PAYDA` varchar(0) DEFAULT NULL,
  `TEVKIFAT` varchar(0) DEFAULT NULL,
  `ALAN_VERGISI` varchar(0) DEFAULT NULL
);

CREATE TABLE `STOK_KARTI` (
  `ID` varchar(0) DEFAULT NULL,
  `STOK_KODU` varchar(0) DEFAULT NULL,
  `STOK_ADI` varchar(0) DEFAULT NULL,
  `KDV` varchar(0) DEFAULT NULL,
  `BIRIM` varchar(0) DEFAULT NULL,
  `BIRIM_FIYAT` varchar(0) DEFAULT NULL,
  `KDV_DURUM` varchar(0) DEFAULT NULL,
  `OZEL_ALAN` varchar(0) DEFAULT NULL
);

CREATE TABLE `TANIMLAR` (
  `ID` tinyint(4) DEFAULT NULL,
  `SERI` varchar(1) DEFAULT NULL,
  `FATURA_NO` smallint(6) DEFAULT NULL,
  `PARA_ONDALIK` tinyint(4) DEFAULT NULL,
  `MIKTAR_ONDALIK` tinyint(4) DEFAULT NULL,
  `VARSAYILAN_KDV` tinyint(4) DEFAULT NULL,
  `VARSAYILAN_KDV_DURUM` tinyint(4) DEFAULT NULL,
  `DIP_NOTLAR` bigint(20) DEFAULT NULL,
  `VARSAYILAN_ACIKLAMA` bigint(20) DEFAULT NULL,
  `TEVKIFAT_PAY` tinyint(4) DEFAULT NULL,
  `TEVKIFAT_PAYDA` tinyint(4) DEFAULT NULL
);
