/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tr.isparta.edu.tr;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author drhal
 */
public class Soru1 extends javax.swing.JFrame {

    static ArrayList<Integer> tamSayilar = new ArrayList<>();
    static ArrayList<Double> ondalikliSayilar = new ArrayList<>();
    String ondalikliSayilarYol = "", tamSyilarYol = "";
    /**
     * Creates new form Soru1
     */
    public Soru1() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBGirisDosyasi = new javax.swing.JButton();
        JBOndalikliAktar = new javax.swing.JButton();
        jBTamsayilariAktar = new javax.swing.JButton();
        jBAktar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBGirisDosyasi.setText("Giriş Dosyası");
        jBGirisDosyasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGirisDosyasiActionPerformed(evt);
            }
        });

        JBOndalikliAktar.setText("Ondalıklıları Aktar");
        JBOndalikliAktar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBOndalikliAktarActionPerformed(evt);
            }
        });

        jBTamsayilariAktar.setText("Tam Sayıları Aktar");
        jBTamsayilariAktar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTamsayilariAktarActionPerformed(evt);
            }
        });

        jBAktar.setText("Aktar");
        jBAktar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAktarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jBGirisDosyasi, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBAktar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JBOndalikliAktar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBTamsayilariAktar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBGirisDosyasi)
                    .addComponent(JBOndalikliAktar)
                    .addComponent(jBTamsayilariAktar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBAktar)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBGirisDosyasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGirisDosyasiActionPerformed
        JFileChooser dosyaSec = new JFileChooser();

        int result = dosyaSec.showOpenDialog(this);
        String yol = "";
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = dosyaSec.getSelectedFile();
            yol = selectedFile.getAbsolutePath();
        }
        if (yol != "") {
            try {
                Scanner scanner = new Scanner(new File(yol));
                while (scanner.hasNextLine()) {
                    String[] satir = scanner.nextLine().split("   ");
                    for (int i = 0; i < satir.length; i++) {
                        if (i % 2 == 0) {
                            tamSayilar.add(Integer.valueOf(satir[i]));
                        } else {
                            ondalikliSayilar.add(Double.valueOf(satir[i]));
                        }
                    }
                }
              
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Soru1.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jBGirisDosyasiActionPerformed

    private void JBOndalikliAktarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBOndalikliAktarActionPerformed
        JFileChooser dosyaSec = new JFileChooser();

        int result = dosyaSec.showOpenDialog(this);
        String yol = "";
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = dosyaSec.getSelectedFile();
            ondalikliSayilarYol = selectedFile.getAbsolutePath();
        }
       
    }//GEN-LAST:event_JBOndalikliAktarActionPerformed

    private void jBAktarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAktarActionPerformed
     
        try {
            FileWriter yaz = new FileWriter(ondalikliSayilarYol);
            PrintWriter printWriter = new PrintWriter(yaz);
            for (int i = 0; i < ondalikliSayilar.size(); i++) {
                if(i > 0 && i % 3 == 0)
                    printWriter.print("\n");
                 printWriter.print(String.valueOf(ondalikliSayilar.get(i)+"   "));
            }
            printWriter.close();
        } catch (IOException ex) {
            Logger.getLogger(Soru1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            FileWriter yaz = new FileWriter(tamSyilarYol);
             PrintWriter printWriter = new PrintWriter(yaz);
            for (int i = 0; i < tamSayilar.size(); i++) {
                if(i > 0 && i % 3 == 0)
                     printWriter.print("\n");
                 printWriter.print(String.valueOf(tamSayilar.get(i)+"   "));
            }
            printWriter.close();
        } catch (IOException ex) {
            Logger.getLogger(Soru1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        JOptionPane.showMessageDialog(this, "Aktarım tamamlandı");
    }//GEN-LAST:event_jBAktarActionPerformed

    private void jBTamsayilariAktarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTamsayilariAktarActionPerformed
        JFileChooser dosyaSec = new JFileChooser();

        int result = dosyaSec.showOpenDialog(this);
        String yol = "";
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = dosyaSec.getSelectedFile();
            tamSyilarYol = selectedFile.getAbsolutePath();
        }
    }//GEN-LAST:event_jBTamsayilariAktarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Soru1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Soru1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Soru1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Soru1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Soru1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBOndalikliAktar;
    private javax.swing.JButton jBAktar;
    private javax.swing.JButton jBGirisDosyasi;
    private javax.swing.JButton jBTamsayilariAktar;
    // End of variables declaration//GEN-END:variables
}
